### ISSUE TITLE
Getting an error after importing this project into eclipse

### ISSUE THREAD

**Issue by charlesfinley** [awslabs/aws-photosharing-example#1]
com.amazon.photosharing.dao.DictionaryPK is not mapped as an embeddable	

Dictionary.java	

/aws-photosharing-example/src/main/java/com/amazon/photosharing/dao
	
line 42	

JPA Problem

**Comment by smoell** [comment]
Which Eclipse version are you using?

**Comment by charlesfinley** [comment]
Using Neon.3 Release (4.6.3)
Java: 1.8.0_131

**Comment by charlesfinley** [comment]
Updated to _151 and getting same error still. :(

**Comment by smoell** [comment]
OK, I'll check tomorrow with the exact same version. Do you have any additional plugins installed?

**Comment by smoell** [comment]
Couldn't reproduce the issue, also worked with Eclipse 4.6.3.

**Comment by charlesfinley** [comment]
@smoell I deleted the project and did a fresh import into eclipse neon 4.6.3. Still having the same issue. Could you suggest any troubleshooting steps?

**Comment by charlesfinley** [comment]
I updated to Oxygen thinking maybe it would help. 

I am having the same issue in Eclipse Oxygen Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200

**Comment by charlesfinley** [comment]
I did a fresh install of eclipse neon on Windows, a fresh install of JDK and imported the project. I get the exact same error on the other machine as well. The original error was on my Mac.
